name: HDR Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080806'
    - '#53515c'
    - '#e79f00'
    - '#004e2e'
    - '#c7a288'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
